DROP TABLE IF EXISTS cliente CASCADE;

DROP TABLE IF EXISTS strumento CASCADE;

DROP TABLE IF EXISTS metododipagamento CASCADE;

DROP TABLE IF EXISTS aggiunto;
DROP TABLE IF EXISTS classificazione;
DROP TABLE IF EXISTS foto;
DROP TABLE IF EXISTS marca;
DROP TABLE IF EXISTS ordine;
DROP TABLE IF EXISTS puntodiconsegna;

DROP DOMAIN livello;
DROP DOMAIN tipocliente;
