CREATE DOMAIN livello AS VARCHAR(15)
 CHECK( VALUE IN('PRINCIPIANTE', 'INTERMEDIO', 'AVANZATO', 'ND') );

 CREATE DOMAIN tipoCliente AS VARCHAR(15)
  CHECK( VALUE IN(
  'OCCASIONALE',
  'PROFESSIONISTA',
  'TITOLARE',
  'ADMIN') );