CREATE DOMAIN livello AS VARCHAR(15)
 CHECK( VALUE IN('PRINCIPIANTE', 'MEDIO', 'AVANZATO') );

 CREATE DOMAIN tipoCliente AS VARCHAR(15)
  CHECK( VALUE IN(
  'OCCASIONALE',
  'PROFESSIONISTA',
  'TITOLARE',
  'ADMIN') );