INSERT INTO Marca(nome)
	VALUES	
		('Casio'),
		('Cort'),
		('DDrum'),
		('DWDrums'),
		('Eko'),
		('Epiphone'),
		('ESP'),
		('Fender'),
		('Gibson'),
		('Gretsch'),
		('Hammond'),
		('Ibanez'),
		('Corg'),
		('Mark Bass'),
		('Marvis'),
		('Meinl'),
		('Musicman'),
		('Ovation'),
		('Paiste'),
		('Pearl'),
		('Remo'),
		('Roland'),
		('Sabian'),
		('Sonor'),
		('TAMA'),
		('Warwick'),
		('Yamaha'),
		('Zildjian');
		
UPDATE Marca SET nome=upper(nome);